# Project
version=1.1.0
group=sircow.reverbcompass
java_version=25

# Common
minecraft_version=26.2
mod_name=Reverb Compass
mod_author=Sir_Cow, Perpillow
mod_id=reverbcompass
license=LGPL-3.0-only
credits=
description=Adds waypoint teleportation to the game as a vanilla-esque feature.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3
modmenu_version=20.0.0-beta.2

# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.configuration-cache=false